


CREATE OR REPLACE PACKAGE PKG_SUELDOS_VENDEDORES
IS
    v_asign_especial NUMBER := 0;
    PROCEDURE PA_INSERTA_ERRORS(p_rutina VARCHAR2, p_mserr VARCHAR2);
    FUNCTION FN_PCT_ANTIGUEDAD(v_rut NUMBER) RETURN NUMBER;
    FUNCTION FN_COMIS_VTA(v_rut NUMBER, p_per VARCHAR2) RETURN NUMBER;
    FUNCTION FN_ASIGNACION_FAMILIAR(v_rut NUMBER) RETURN NUMBER;
    PROCEDURE PA_PRINCIPAL (p_prediodo VARCHAR2);

END PKG_SUELDOS_VENDEDORES;
/
